create table if not exists public.agent_token_usage (
  id bigint generated by default as identity primary key,
  agent_id text not null,
  run_id text not null,
  task_name text,
  model text,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  total_tokens integer generated always as (coalesce(input_tokens, 0) + coalesce(output_tokens, 0)) stored,
  estimated_cost_usd numeric(12,6),
  status text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  meta jsonb
);

create unique index if not exists uq_agent_token_usage_agent_run
  on public.agent_token_usage(agent_id, run_id);

create index if not exists idx_agent_token_usage_created_at
  on public.agent_token_usage(created_at desc);

create index if not exists idx_agent_token_usage_agent_created_at
  on public.agent_token_usage(agent_id, created_at desc);
